// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Zain_TitleSkip","status":true,"description":"Makes it so the default title screen is skipped when booting up the game and after a gameover.","parameters":{}},
{"name":"Discord_Connect","status":true,"description":"[RPG Maker MZ] [DiscordConnect] [up]","parameters":{"varName":"SatoshiFlowersToken"}},
{"name":"ethers.umd.min","status":true,"description":"","parameters":{}},
{"name":"Web3","status":true,"description":"[RPG Maker MZ] [Web3] [up]","parameters":{"ethStatusVariable":"22"}},
{"name":"Stamina","status":true,"description":"Manage the Stamina Bar","parameters":{"varId":"6"}},
{"name":"Satoshi_Bee","status":true,"description":"[RPG Maker MZ] [Satoshi_Bee Minigame]","parameters":{"statusVariable":"25"}}
];
